#!/bin/bash

# make my env
# this is weird and specific

# set debug
if [[ $1 == -d ]]; then
    DEBUG=1
else
    DEBUG=0
fi

# made in to $HOME/
DEFAULT_DIRS=(
    'proj'
    '.config/coc'
    'unsort'
    'clone'
    'Venv'
    'Downloads'
    'Pictures'
    'Documents'
)


aur_helper_name='paru'
aur_helper_url='https://aur.archlinux.org/paru.git'

host_char="$( hostname )"
host_char="${host_char:0:1}"

[[ $DEBUG -eq 1 ]] && printf 'starting init script\n'

make_env_dirs() {
    local dirs

    dirs_to_make=( $@ )

    [[ $DEBUG -eq 1 ]] && printf '\nmaking default dirs:\n\n'

    for to_make in ${dirs_to_make[@]}; do
        [[ $DEBUG -eq 1 ]] && printf '    %s\n' "$to_make"

        mkdir -p "${HOME}/${to_make}" 2>/dev/null
    done
}

stow_by_key() {
    [[ $DEBUG -eq 1 ]] && printf '\nrunning stow for _%s\n\n' "$1"

    # run stow for all that match *_key,
    #
    # TODO: if there are no directory's named *_key then this will fail,
    # i should fix this
    for to_stow in *_"${1}"; do
        [[ $DEBUG -eq 1 ]] && printf '      %s\n' "$to_stow"

        stow "$to_stow"
    done
}

curl_vim_plug() {
    local url
    url="$1"

    [[ $DEBUG -eq 1 ]] && printf '\ndownloading vim plug\n\n'

    if ! curl -fL "$url" -o /tmp/plug.vim; then
        printf 'could not curl vim plug\n' 1>&2
        return 1
    fi

    [[ $DEBUG -eq 1 ]] && printf '\ncopying vim-plug to vim and nvim dirs\n\n'

    mkdir ~/.local/share/nvim/site/autoload/ &>/dev/null
    cp /tmp/plug.vim ~/.local/share/nvim/site/autoload/plug.vim

    mkdir ~/.vim/autoload/ &>/dev/null
    mv /tmp/plug.vim ~/.vim/autoload/plug.vim
}

install_aur_helper() {
    local part_one helper_name helper_url

    helper_name="$1"
    helper_url="$2"

    mkdir ~/aur &>/dev/null

    if ! cd "${HOME}/aur" ; then
        printf 'cant cd to home/aur; idk what happened\n' 1>&2
        return 1
    fi

    [[ $DEBUG -eq 1 ]] && \
        printf '\ngit cloning cloning the aur helper: %s\n\n' "$aur_helper_name"

    if ! git clone "$aur_helper_url"; then
        printf 'could not clone the aur helper: %s\n' "$aur_helper_url" 1>&2
        return 1
    fi

    if [[ ! -f  ${aur_helper_name}/PKGBUILD ]]; then
        printf 'no PKGBUILD in aur helper project: %s\n' "$aur_helper_name" 1>&2
        return 1
    fi

    if ! cd "$helper_name" ; then
        printf 'cant cd in to ~/aur/%s' "$aur_helper_name" 1>&2
        return 1
    fi

    [[ $DEBUG -eq 1 ]] && printf '\nrunning makepkg -isc PKGBUILD\n\n'

    makepkg -isc
}

# make default dirs
make_env_dirs "${DEFAULT_DIRS[@]}"

# run stow_by_key with all
stow_by_key 'all'

# get the first char of the host name and run stow_by_key with it
stow_by_key "$host_char"

# add vim-plug to env
if [[ ! -f ~/.local/share/nvim/site/autoload/plug.vim ]]; then
    curl_vim_plug \
        'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi

if ! command -v $aur_helper_name &>/dev/null; then
    install_aur_helper "$aur_helper_name" "$aur_helper_url"
fi

[[ $DEBUG -eq 1 ]] && printf '\ninit script is done\n'
