[all]
hypr.from = "hypr"
hypr.to = "~/.config/hypr"
fish.from = "fish"
fish.to = "~/.config/fish"
kitty.from = "kitty"
kitty.to = "~/.config/kitty"
star.from = "starship/starship.toml"
star.to = "~/.config/starship.toml"
nvim.from = "nvim"
nvim.to = "~/.config/nvim"
mpv.from = "mpv"
mpv.to = "~/.config/mpv"
skel.from = "skel"
skel.to = "~/.config/skel"
git.from = "git/gitconfig"
git.to = "~/.gitconfig"
bin.from = "bin"
bin.to = "~/bin"
bash.from = "bash/*"
bash.to = "~/*"
