# see link for formating and module info
# https://starship.rs/config/#prompt

# format = '''[┌─╼](blue) $directory$jobs$git_status$git_branch$nodejs$python
format = '''[┌─╼](blue) $directory$jobs$git_status$git_branch
[└──▶](blue) '''

add_newline = false

[directory]
style = 'purple'
truncate_to_repo = false
truncation_length = 0

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'

[git_branch]
format = '[$symbol$branch]($style) '
style = 'cyan'
