dirs = [
    "src",
    "out",
]

files = []

build = """
git init
"""

[[templates]]
path = "src/main.cc"
include = "{{config-dir}}/projects/cc_basic/main.cc"

[[templates]]
path = "justfile"
include = "{{config-dir}}/projects/cc_basic/justfile"

[[templates]]
path = ".gitignore"
include = "{{config-dir}}/projects/cc_basic/cc.gitignore"

[[templates]]
path = ".clang_format"
include = "{{config-dir}}/projects/cc_basic/clang_format.yaml"
