dirs = [ "src" ]

build = """
yarn init _y _cwd '{{root}}'
yarn add _cwd '{{root}}' 'eslint'
"""

[[templates]]
path = "src/main.js"
include = "{{config_dir}}/projects/basic_javascript/main.js"

[[templates]]
path  = ".eslintrc.json"
include = "{{config_dir}}/projects/basic_javascript/javascript.eslintrc.json"
