[[templates]]
path = "src/main.lua"
template = """local function main()
    print("hello world")
end

main()
"""

[[templates]]
path = ".luarc.json"
template = """
{
    "Lua.format.defaultConfig": {
        "indent_style": "space",
        "indent_size": "2",
        "quote_style": "double",
        "max_line_length": 80,
        "call_arg_parentheses": "remove_table_only"
    }
}
"""
