dirs = [
    "src",
    "out",
]

files = []

[[templates]]
path = "src/main.cpp"
include = "{{config-dir}}/projects/cpp_basic/main.cpp"

[[templates]]
path = "Makefile"
include = "{{config-dir}}/projects/cpp_basic/Makefile"

[[templates]]
path = ".clang-format"
include = "{{config-dir}}/projects/cpp_basic/clang_format.yaml"
