return {
  dir = "~/proj/abrev.nvim",
  -- "chrisrhayden/abrev.nvim",
  opts = {
    abrevs = {
      { "b{r,ra,re,rea,ear}k{,e}", "break", },
      { "clieant{,s}", "client{,s}", },
      { "creat", "crate", },
      { "lein", "line", },
      { "liek", "like", },
      { "nedl", "endl", },
      { "ot", "to", },
      { "sdt", "std", },
      { "shitf", "shift", },
      { "sl{ef,fe}", "self", },
      { "som{,t,th}ing", "something", },
      { "everytihng", "everything", },
      { "statice", "static", },
      { "{teh,hte}", "the", },
      { "paht", "path", },
      { "tets", "test", },
      { "thay", "they", },
      { "ting", "thing", },
      { "tsd", "std", },
      { "useing", "using", },
      { "viod", "void", },
      { "wpgu", "wgpu", },
      { "yeald", "yield", },
      { "m{,e}sg", "message", },
      { "m{,e}sgs", "messages", },
      { "obj{,s}", "object{,s}", },
      { "anme", "name", },
      { "stroing", "string", },
      { "p{,i}xl{,e}", "pixel", },
      { "in{it,ti}ng", "initializing", },
      { "titel", "title", },
      { "hashamp", "hashMap", },
      { "rnage", "range", },
      { "javascrpt", "JavaScript", },
      { "whlie", "while" },
      { "seom", "some" },
    }
  },
}
