#!/bin/bash

# Custom Rofi Script

# Launch Rofi
MENU="$(
    rofi -config ~/.dots/scripts/rofi/right_aligned_config.rasi -dmenu -sep '|' \
        <<< "  Lock|  Logout|  Reboot|  Shutdown"
)"

case "$MENU" in
  *Lock) ~/bin/blurlock ;;
  *Logout) openbox --exit;;
  *Reboot) systemctl reboot ;;
  *Shutdown) systemctl -i poweroff
esac

# More Options
# -fullscreen \

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
