# colors {{{
CONFIG_SHADE1="#311B92"
CONFIG_SHADE2="#4527A0"
CONFIG_SHADE3="#512DA8"
CONFIG_SHADE4="#5E35B1"
CONFIG_SHADE5="#673AB7"
CONFIG_SHADE6="#7E57C2"
CONFIG_SHADE7="#9575CD"
CONFIG_SHADE8="#B39DDB"

CONFIG_BLACK="#000000"
CONFIG_WHITE="#ffffff"
CONFIG_RED="#e53935"
CONFIG_GREEN="#43a047"
CONFIG_YELLOW="#fdd835"
CONFIG_BLUE="#1e88e5"
CONFIG_MAGENTA="#00897b"
CONFIG_CYAN="#00acc1"
CONFIG_PINK="#d81b60"
CONFIG_PURPLE="#8e24aa"
CONFIG_INDIGO="#3949ab"
CONFIG_TEAL="#00897b"
CONFIG_LIME="#c0ca33"
CONFIG_AMBER="#ffb300"
CONFIG_ORANGE="#fb8c00"
CONFIG_BROWN="#6d4c41"
CONFIG_GREY="#757575"
CONFIG_BLUE_GREY="#546e7a"
CONFIG_DEEP_PURPLE="#5e35b1"
CONFIG_DEEP_ORANGE="#f4511e"
CONFIG_LIGHT_BLUE="#039be5"
CONFIG_LIGHT_GREEN="#7cb342"
CONFIG_BORDER="#0f0f0f"
CONFIG_SEPARATOR="#191919"
CONFIG_FOREGROUND="#A9ABB0"

# CONFIG_BACKGROUND="#1F1F1F"
CONFIG_BACKGROUND="#191919"
CONFIG_BACKGROUND_ALT="#252525"
CONFIG_HIGHLIGHT_BACKGROUND="#311B92"
CONFIG_HIGHLIGHT_FOREGROUND="#FFFFFF"
# }}}

# layout {{{
CONFIG_OFFSET=10
# }}}

# rofi {{{
CONFIG_ROFI_X_OFFSET="$CONFIG_OFFSET"
CONFIG_ROFI_Y_OFFSET=$((($CONFIG_OFFSET * 2) + 26))

CONFIG_ROFI_WINDOW="$CONFIG_BACKGROUND,$CONFIG_BORDER,$CONFIG_SEPARATOR"
CONFIG_ROFI_NORMAL="$CONFIG_BACKGROUND_ALT,$CONFIG_FOREGROUND,$CONFIG_BACKGROUND_ALT,$CONFIG_HIGHLIGHT_BACKGROUND,$CONFIG_HIGHLIGHT_FOREGROUND"
CONFIG_ROFI_ACTIVE="$CONFIG_BACKGROUND,$CONFIG_MAGENTA,$CONFIG_BACKGROUND_ALT,$CONFIG_HIGHLIGHT_BACKGROUND,$CONFIG_HIGHLIGHT_FOREGROUND"
CONFIG_ROFI_URGENT="$CONFIG_BACKGROUND,$CONFIG_YELLOW,$CONFIG_BACKGROUND_ALT,$CONFIG_HIGHLIGHT_BACKGROUND,$CONFIG_HIGHLIGHT_FOREGROUND"
# }}}
