#!/bin/bash

# Custom Rofi Script

if [[ -f ${HOME}/.dots/scripts/config_vars.sh ]]; then
    source "${HOME}/.dots/scripts/config_vars.sh"
else
    echo 'pleas set env colors'
    exit 1
fi

# Launch Rofi
MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'System :' \
-hide-scrollbar true \
-bw 0 \
-lines 4 \
-line-padding 10 \
-padding 20 \
-width 15 \
-location 5 \
-xoffset -"$CONFIG_ROFI_X_OFFSET" \
-yoffset -"$CONFIG_ROFI_Y_OFFSET" \
-columns 1 \
-show-icons -icon-theme "Papirus" \
-font "Fantasque Sans Mono 10" \
-color-enabled true \
    -color-window "$CONFIG_ROFI_WINDOW" \
    -color-normal "$CONFIG_ROFI_NORMAL" \
    -color-active "$CONFIG_ROFI_ACTIVE" \
    -color-urgent "$CONFIG_ROFI_URGENT" \
<<< "  Lock|  Logout|  Reboot|  Shutdown")"

case "$MENU" in
  *Lock) ~/bin/blurlock ;;
  *Logout) openbox --exit;;
  *Reboot) systemctl reboot ;;
  *Shutdown) systemctl -i poweroff
esac

# More Options
# -fullscreen \

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
